# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('joined_date', models.DateField()),
                ('salary', models.FloatField()),
                ('phone', models.CharField(max_length=50)),
                ('performance_indice', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('children_number', models.IntegerField()),
                ('adress', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('married', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Notation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='notation',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Widget'),
        ),
    ]
